### ISSUE TITLE
Update examples using metalsmith-templates to metalsmith-layouts

### ISSUE THREAD

**Issue by ismay** [segmentio/metalsmith.io#109]
The code examples use the now deprecated metalsmith-templates.

Also, maybe it would save newcomers time if the deprecation for metalsmith-templates would be immediately visible in its entry in the `the plugins` section, preferably with a link to metalsmith-layouts. Saves them from having to go to the repository and see that it's been deprecated.

**Comment by lambtron** [comment]
We can update that, good point. Thank you!
