### ISSUE TITLE
Rebuild site

### ISSUE THREAD

**Issue by ismay** [segmentio/metalsmith.io#127]
Several plugins have been added to `plugins.json`, but they're not yet visible on metalsmith.io since the site hasn't been rebuilt.

**Comment by lambtron** [comment]
One of the maintainers is going to transfer ownership to the Heroku to us. Thanks for your patience.

**Comment by Ajedi32** [comment]
It's hosted on Heroku? Interesting. I guess I just assumed it was hosted on GitHub pages, since it appears to be a static site.

**Comment by lambtron** [comment]
Site is rebuilt!! Haha yes, it's on heroku. :)

**Comment by ismay** [comment]
Awesome, thanks!
