### ISSUE TITLE
Down?

### ISSUE THREAD

**Issue by kud** [segmentio/metalsmith.io#139]
![windows-2015-11-19-23 08 52](https://cloud.githubusercontent.com/assets/655838/11285965/93212250-8f12-11e5-9c6b-587f9b47ea95.png)

**Comment by Ajedi32** [comment]
:+1: Yeah, looks down for me too.

**Comment by kud** [comment]
![macosx-2015-11-20-at-10 20 19](https://cloud.githubusercontent.com/assets/655838/11296102/5963313a-8f70-11e5-886b-09f02a543ece.png)

https://twitter.com/andyjiang/status/667524985452298240

**Comment by Ajedi32** [comment]
Looks like it's fixed.

**Comment by kud** [comment]
Indeed, thanks!
