### ISSUE TITLE
How to build the site ?

### ISSUE THREAD

**Issue by jocelynlecomte** [segmentio/metalsmith.io#75]
While trying to submit my plugin, I tried to build the site but nothing happened. It seems your build.js use more complex tools than the ones I'm used to. Could you please explain how to build ?

**Comment by ianstormtaylor** [comment]
Hey! If you have `node` and `npm` installed, then running `make server` should actually install all of the dependencies and start the server for you, which will rebuild whenever it is requested.

Hope that helps!
